batch_size: 512
dataset: ISCX
dataset_root: '/home/cape/data/trace/ISCXTor2016/MyFlowPic'
flag: True
epochs: 100
loss_func: nn.CrossEntropyLoss()
model: FlowPicNet(self.num_classes)
lr: 0.001
lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.6,patience=2)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9,0.999])
