batch_size: 128
checkpoint_folder_name: FlowPicNet-ISCXTor2016_nonTor-Adam-ReduceLROnPlateau-2023-10-26_00-56-47
dataset: ISCX
dataset_root: D:\data\trace\processed\ISCXTor2016\FlowPic
epochs: 100
flag: false
loss_func: nn.CrossEntropyLoss()
lr: 0.001
lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.6,patience=2)
model: FlowPicNet(self.num_classes)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9, 0.999])
