batch_size: 128
checkpoint_folder_name: FlowPicNet-ISCXVPN2016-VPN-Adam_ReduceLROnPlateau-2023-10-25_13-48-06
dataset: ISCX
dataset_root: D:\data\trace\processed\ISCXVPN2016\FlowPic
epochs: 100
flag: Ture
loss_func: nn.CrossEntropyLoss()
lr: 0.001
lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.6,patience=2)
model: FlowPicNet(self.num_classes)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9, 0.999])
