#有key无value的默认为None
debug: False # debug模式下不保存信息
grad: False # grad控制是否打印梯度信息
batch_size: 64

# 这个参数方便切换不同数据集，更加灵活
dataset_root: '/home/cape/code/FlowPic-main/datasets' # 测试
#dataset_root: '/home/cape/data/trace' # 测试old dataset

dataset: Video_VoIP_splited #VoIP_Video_Application_NonVPN
# 使用的是不平衡的数据集
feature_method:  DELTA_T=15-IMG_DIM=32 #MiniTest # 这是长度60s的窗口, test_radio=0.1
#feature_method: JointFeature
train_csv_file: train.csv #train-before-transform.csv
test_csv_file: #test-ChangeRTT.csv
val_csv_file: #val.csv

transform: #PacketLoss
#target_transform: ToTensor
shuffle: True
epochs: 40

loss_func: nn.CrossEntropyLoss()

model: MiniFlowPicNet_32(self.num_classes) # PCA = None
#model: FlowPicNet_adaptive(self.num_classes,liner1_in_feature=4500) # liner1_in_feature=9000 if joint
#model: PureClassifier(num_classes=self.num_classes,in_features=9000,out_features=100)
lr: 0.001
#lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.8,patience=3)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9,0.999])