batch_size: 256
# 这个参数方便切换不同数据集，更加灵活
dataset_root: '/home/cape/data/trace/new_processed' # 测试
#dataset_root: '/home/cape/data/trace' # 测试old dataset
dataset: ISCXTor2016_nonTor

#feature_method: FlowPic
feature_method: JointFeature_trained_nonTor_model

shuffle : True
epochs: 80
loss_func: nn.CrossEntropyLoss()

#model: FlowPicNet_adaptive(self.num_classes,liner1_in_feature=4500)
model: PureClassifier(num_classes=self.num_classes,in_features=9000,out_features=100)
lr: 0.0005
lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.6,patience=2)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9,0.999])
