batch_size: 128
dataset: ISCXTor2016_nonTor
feature_method: Joint
shuffle : True

epochs: 100
loss_func: nn.CrossEntropyLoss()
# self.num_classes 来自数据集,而后者来自错误运行报错
model: FlowPicNet_adaptive(self.num_classes,liner1_in_feature=9000)
lr: 0.001
lr_scheduler: ReduceLROnPlateau(self.opt,mode='min',factor=0.6,patience=2)
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9,0.999])
