batch_size: 128
checkpoint_folder_name: FlowPicNet-ISCXTor2016_EIMTC-Adam_0.001
dataset: ISCXTor2016_EIMTC
dataset_root: D:\data\trace\ISCXTor2016\tor\EIMTC-FlowPic
epochs: 100
loss_func: nn.CrossEntropyLoss()
lr: 0.001
lr_scheduler: StepLR(self.optim,10,0.5)
model: FlowPicNet(self.num_classes)
num_classes: 9
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9, 0.999])
time: 2023-10-19_17-50-19
