batch_size: 300
checkpoint_folder_name: FlowPicNet-ISCXTor-Adam_0.001
dataset: ISCXTor
dataset_root: r'D:\data\trace\ISCXTor2016\tor\EIMTC-FlowPic'
epochs: 40
loss_func: nn.CrossEntropyLoss()
lr: 0.001
lr_scheduler: StepLr(self.optim,10,0.5)
model: FlowPicNet(num_classes=10)
num_classes: 10
optim: optim.Adam(params=self.model.parameters(), lr=self.lr,betas=[0.9, 0.999])
time: 2023-10-19_17-38-55
